#!/usr/bin/env sh

# taps
brew tap eddieantonio/eddieantonio
brew tap ethereum/ethereum
brew tap go-delve/delve
brew tap grammarly/tap
brew tap grpc/grpc
brew tap hhvm/hhvm
brew tap homebrew/apache
brew tap homebrew/boneyard
brew tap homebrew/completions
brew tap homebrew/core
brew tap homebrew/dupes
brew tap homebrew/gui
brew tap homebrew/php
brew tap homebrew/python
brew tap homebrew/science
brew tap homebrew/services
brew tap homebrew/versions
brew tap ksonnet/tap
brew tap rstacruz/backup
brew tap zoidbergwill/python

# packages
brew install ack
brew install apr
brew install apr-util
brew install aria2
brew install asciinema
brew install aspcud
brew install aspell
brew install atk
brew install atkmm
brew install augeas
brew install autoconf
brew install autojump
brew install automake
brew install bash
brew install binutils
brew install bison@2.7
brew install boost
brew install boost@1.60
brew install c-ares
brew install cairo
brew install cairomm
brew install camlp4
brew install ccache
brew install certbot
brew install clasp
brew install clingo
brew install cmake
brew install composer
brew install coreutils
brew install cscope
brew install curl
brew install darcs
brew install dbus
brew install delve
brew install dialog
brew install diff-so-fancy
brew install dirmngr
brew install docbook
brew install docker
brew install docker-compose
brew install docker-machine
brew install docker-machine-driver-xhyve
brew install elixir
brew install erlang
brew install ethereum
brew install exa
brew install fasd
brew install figlet
brew install flatbuffers
brew install flex
brew install fontconfig
brew install fortune
brew install fpp
brew install freetype
brew install fzy
brew install gawk
brew install gcc
brew install gcc@5
brew install gd
brew install gdbm
brew install gdk-pixbuf
brew install geoip
brew install gettext
brew install gflags
brew install gibo
brew install git
brew install git-lfs
brew install glib
brew install glibmm
brew install glog
brew install gmp
brew install gnome-doc-utils
brew install gnu-sed
brew install gnu-tar
brew install gnutls
brew install go
brew install gobject-introspection
brew install google-protobuf
brew install googler
brew install gpm
brew install graphicsmagick
brew install graphite2
brew install graphviz
brew install gringo
brew install grpc
brew install gsasl
brew install gsettings-desktop-schemas
brew install gtk+
brew install gtk+3
brew install gtkmm3
brew install gtksourceview3
brew install gzip
brew install harfbuzz
brew install hicolor-icon-theme
brew install highlight
brew install hostess
brew install htop
brew install httpie
brew install hub
brew install hugo
brew install icu4c
brew install iftop
brew install imagemagick
brew install intltool
brew install iproute2mac
brew install isl
brew install isl@0.14
brew install jemalloc
brew install jpeg
brew install jpegoptim
brew install jq
brew install jsoncpp
brew install jsonnet
brew install kompose
brew install ks
brew install kubernetes-cli
brew install kubernetes-helm
brew install lftp
brew install libassuan
brew install libcroco
brew install libelf
brew install libepoxy
brew install libev
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libidn
brew install libinfinity
brew install libksba
brew install libmpc
brew install libnet
brew install libpng
brew install librsvg
brew install libsigc++
brew install libssh2
brew install libtasn1
brew install libtermkey
brew install libtiff
brew install libtool
brew install libtorrent
brew install libunistring
brew install libusb
brew install libusb-compat
brew install libvterm
brew install libxml++
brew install libxml2
brew install libyaml
brew install libzip
brew install little-cms2
brew install lua
brew install luajit
brew install lz4
brew install lzlib
brew install mackup
brew install macvim
brew install makedepend
brew install matplotlib
brew install maven
brew install mcrypt
brew install md5sha1sum
brew install mercurial
brew install mhash
brew install minio
brew install moreutils
brew install mpfr
brew install msgpack
brew install mtr
brew install mysql
brew install neofetch
brew install nettle
brew install newt
brew install ngrep
brew install nmap
brew install node
brew install numpy
brew install nvm
brew install ocaml
brew install ocamlbuild
brew install oniguruma
brew install opam
brew install openssh
brew install openssl
brew install openssl@1.1
brew install ossp-uuid
brew install osxutils
brew install p11-kit
brew install pandoc
brew install pango
brew install pangomm
brew install pcre
brew install peco
brew install php71
brew install pinentry
brew install pixman
brew install pkg-config
brew install pngcrush
brew install pngquant
brew install popt
brew install postgresql
brew install protobuf
brew install pstree
brew install pth
brew install pwgen
brew install pyenv
brew install pyenv-ccache
brew install pyenv-pip-migrate
brew install pyenv-virtualenv
brew install pypy3
brew install pyside
brew install python
brew install python3
brew install qt
brew install rancher-cli
brew install rancher-compose
brew install rbenv
brew install re2
brew install re2c
brew install readline
brew install ripgrep
brew install rocker
brew install ruby-build
brew install rust
brew install s-lang
brew install scons
brew install screenresolution
brew install shared-mime-info
brew install shellcheck
brew install shiboken
brew install snappy
brew install sqlite
brew install ssh-copy-id
brew install stern
brew install swig
brew install tbb
brew install tcptraceroute
brew install terraform
brew install the_silver_searcher
brew install thrift
brew install tldr
brew install tmux
brew install unixodbc
brew install unrar
brew install utf8proc
brew install v8
brew install watch
brew install webp
brew install whois
brew install wxmac
brew install xhyve
brew install xz
brew install yarn
brew install zlib
brew install zplug
brew install zsh --HEAD
brew install zsh-completions
