# Profiling stuff
# PS4=$'\\\011%D{%s%6.}\011%x\011%I\011%N\011%e\011'
# exec 3>&2 2>/tmp/zshstart.$$.log
# setopt xtrace prompt_subst
# set -x
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "zoidbergwill/oh-my-zsh", \
    use:'themes/zoidbergwill.zsh-theme', \
    rename-to:'zoidbergwill.zsh-theme', \
    as:theme
#zplug "b4b4r07/enhancd", at:v1, use:"*.sh"
zplug "lib/clipboard", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"
zplug "lib/directories", from:oh-my-zsh
zplug "lib/key-bindings", from:oh-my-zsh
zplug "lib/termsupport", from:oh-my-zsh
zplug "plugins/colorize", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
# zplug "plugins/globalias", from:oh-my-zsh
zplug "plugins/gnu-utils", from:oh-my-zsh
zplug "plugins/history", from:oh-my-zsh
zplug "plugins/osx", from:oh-my-zsh
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
unsetopt nomatch

CASE_SENSITIVE="true"

DISABLE_UNTRACKED_FILES_DIRTY="true"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
HIST_STAMPS="dd/mm/yyyy"

HISTSIZE=1000000
HISTFILE=~/.zsh_history
SAVEHIST=1000000
setopt inc_append_history share_history
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_save_no_dups

. ~/.zsh/docker.zsh
. ~/.zsh/erlang.zsh
. ~/.zsh/general.zsh
. ~/.zsh/git.zsh
. ~/.zsh/go.zsh
. ~/.zsh/h.zsh
. ~/.zsh/javascript.zsh
. ~/.zsh/kubectl.zsh
. ~/.zsh/osx.zsh
. ~/.zsh/prompt.zsh
. ~/.zsh/python.zsh
. ~/.zsh/terraform.zsh
. ~/.zsh/work.zsh
. ~/.zsh/perl.zsh

if [[ -d ~/src/private-dotfiles ]]; then
  . ~/src/private-dotfiles/zshrc-extras
fi

zstyle ':completion:*' menu select=2

# export TERM="xterm-256color"

fpath=(~/.zsh/completion /usr/local/share/zsh-completions $fpath)

export PATH="/usr/local/opt/ruby/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/local/sbin:${HOME}/.composer/vendor/bin:$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:${HOME}/.gem/ruby/2.5.0/bin:/usr/local/opt/ccache/libexec:/usr/local/opt/php71/bin:$PATH:${HOME}/.conduit/bin:${HOME}/src/istio/bin:/usr/local/share/zsh/site-functions:${HOME}/src/apps/istio-0.1.6/bin"
export CDPATH="${CDPATH}:${HOME}/src:${HOME}/work:${HOME}/src/go/src"

if [ -f '${HOME}/src/apps/google-cloud-sdk/path.zsh.inc' ]; then
    source '${HOME}/src/apps/google-cloud-sdk/path.zsh.inc';
fi
if [ -f '${HOME}/src/apps/google-cloud-sdk/completion.zsh.inc' ]; then
    source '${HOME}/src/apps/google-cloud-sdk/completion.zsh.inc';
fi

#alias vim=nvim
#
function view_ssl_cert() {
    echo | openssl s_client -showcerts -servername "$1" -connect "$1":443 2>/dev/null | openssl x509 -inform pem -noout -text
}

if ! zplug check; then
    printf "Found zplug updates. Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

unalias h

if zplug check b4b4r07/enhancd; then
  export ENHANCD_FILTER=fzy
fi

alias fzfe='fzf --bind "enter:execute(vim {})'
alias fzfl='fzf --bind "enter:execute(less {})'
alias rvscode="${HOME}/work/nuclide/modules/big-dig-vscode/scripts/mac-insiders-dev"

# add Pulumi to the PATH
export PATH="$PATH:$HOME/.pulumi/bin:$HOME/src/apps/arcanist/bin/"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '${HOME}/src/apps/google-cloud-sdk/path.zsh.inc' ]; then source '${HOME}/src/apps/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '${HOME}/src/apps/google-cloud-sdk/completion.zsh.inc' ]; then source '${HOME}/src/apps/google-cloud-sdk/completion.zsh.inc'; fi

# opam configuration
# test -r ${HOME}/.opam/opam-init/init.zsh && . ${HOME}/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
alias ssh="TERM=xterm-256color ssh"
alias d="kitty +kitten diff"

# eval "$(rbenv init -)"

export GREP_OPTIONS="--color=auto"

#
# Profiling stuff
# set +x
# unsetopt xtrace
# exec 2>&3 3>&-
#
# export PATH="/usr/local/opt/llvm/bin:$PATH"
# export LDFLAGS="-L/usr/local/opt/llvm/lib"
# export CPPFLAGS="-I/usr/local/opt/llvm/include"
# [ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
# export KEYFILE="${HOME}/.config/void.keys"
#
alias icat="kitty +kitten icat"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH="/usr/local/opt/mozjpeg/bin:$PATH"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH:/usr/local/opt/grep/libexec/gnubin"
